# Site settings
name: Satnam Singh
title: Satnam Singh | Swift Developer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://silverseahog.com/
baseurl: ''
email: 29satnam@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://29satnam.github.io/resume.pdf
social:
  - title: email
    url: mailto:29satnam@gmail.com
  - title: twitter
    url: https://twitter.com/codetard
  - title: instagram
    url: https://instagram.com/codetard
  - title: codepen
    url: http://codepen.io/Satnam-the-bold
  - title: github
    url: https://github.com/29satnam
  - title: linkedin
    url: https://www.linkedin.com/in/satnam-singh-948348aa/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
